spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/warp3}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DATABASE_USER:warp3}
spring.datasource.password=${DATABASE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.h2.console.enabled=false

spring.thymeleaf.cache=true
