spring.application.name=warp3.lu

server.port=8080

spring.datasource.url=jdbc:h2:file:./data/cmsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.thymeleaf.cache=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# External events sync (Semantic MediaWiki JSON endpoint)
events.external.url=https://wiki.syn2cat.lu/wiki/Special:Ask/-5B-5BCategory:Event-5D-5D-20-5B-5BStartDate::%2B-5D-5D/-3FStartDate/-3FEndDate/-3FHas-20subtitle/-3FHas-20description/-3FIs-20Event-20of-20Type/-3FHas-20location/-3FHas-20picture/-3FHas-20cost/format%3Djson/sort%3DStartDate/order%3Dascending/limit%3D500